### ISSUE TITLE
Number of endpoints approximation 

### ISSUE THREAD

**Issue by ckyiricky** [googleinterns/k8s-topology-simulator#7]
Commit Hash: f098657ab704266322c08d42eadfba4207b65b0b
In algorithm 2 (maybe in alg1 as well),  
1. The approximation on number of endpoints when doing distribution among zones, causes inaccurate result: 
i.e.  -27.43 69.68 -43.21 0.98 these four numbers, with rounding approximation, it ends up with -27 70 -43 1. With floor approximation it ends up with -27, 69, -43, 0. either way is not the answer we want.
2. The order of the zones being processed impact the final distribution based on the issue above.

**Comment by robscott** [comment]
Do you think we can consider this fixed by #6?

**Comment by ckyiricky** [comment]
> Do you think we can consider this fixed by #6?

Yeah, I think so. We could close this issue.
